"""empty message

Revision ID: 651d36471fb8
Revises: 7b414d54d612
Create Date: 2018-06-15 17:18:06.737001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '651d36471fb8'
down_revision = '7b414d54d612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('path', postgresql.ARRAY(sa.String(length=128), dimensions=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'path')
    # ### end Alembic commands ###
